spring:
  application:
    name: loan
  security.oauth2.resourceserver.jwt.issuer-uri: https://idp.tanermansur.com/issuer
  jpa.open-in-view: false
  jackson.default-property-inclusion: NON_NULL
  datasource:
    url: jdbc:h2:mem:loan
    driver-class-name: org.h2.Driver